### ISSUE TITLE
1.18.2?

### ISSUE THREAD

**Issue by enderprism** [MightyKnight/ShieldDisruptor#1]
When will this mod be updated to 1.18.2?

**Comment by MightyKnight** [comment]
Hi,
sorry for not noticing your comment, I've had to deal with a longer break. and might have missed the email from Github.
Anyway, I returned and there's a 1.19 version now.

Do you still think you need it for 1.18.2?

**Comment by enderprism** [comment]
No, 1.18.2 is not needed anymore. Thank you! In the meantime I used a VanillaTweaks resourcepack which lowered the shield a bit.
I'm closing the issue.
